### PR TITLE
Can hash more?

### PR DESCRIPTION
**Pull request by glassresistor**
Just some extra good stuff for getting sets and things dependent on hash working.

### CODE REVIEW

**Comment by glassresistor** [comment]
Ok so its now tested and working.

**Comment by atl** [comment]
You're right in focusing in on self.id, but it is already a UUID, and therefore has a natural (long)int form. Longs are acceptable since Py2.5 as hash values.

**Comment by glassresistor** [comment]
Cool, i couldn't find a confirming doc that it was always going to fit into
that frame.  Thats its also work setting a property on the object so hash
can be called multiple time.

On Fri, Dec 7, 2012 at 6:13 AM, Adam Lindsay notifications@github.comwrote:

> You're right in focusing in on self.id, but it is already a UUID, and
> therefore has a natural (long)int form. Longs are acceptable since Py2.5 as
> hash values.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/atl/py-smartdc/pull/4#issuecomment-11131142.

## 

Michael

**Comment by atl** [comment]
new release is up and on pypi. give it a test!

**Comment by glassresistor** [comment]
Thanks I say it doing it now off my local branch.

On Fri, Dec 7, 2012 at 8:05 AM, Adam Lindsay notifications@github.comwrote:

> new release is up and on pypi. give it a test!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/atl/py-smartdc/pull/4#issuecomment-11135264.

## 

Michael

**Pull request closed without merging**
